### ISSUE TITLE
Logout Button is not working

### ISSUE THREAD

**Issue by Kool-Cool** [Kool-Cool/StudentPortal#1]
https://github.com/Kool-Cool/StudentPortal/blob/d9ee77eeb6fac6ea64c1dcf0873c7819bc71ccd1/templates/base.html#L19

Need working Logout Button 
which will terminate the session

**Comment by zitaker** [comment]
![image](https://github.com/Kool-Cool/StudentPortal/assets/92075508/e3b304ed-c074-440d-81a9-0df18a982503)
Hi! How do I log in to the session first?

**Comment by Kool-Cool** [comment]
https://github.com/Kool-Cool/StudentPortal/blob/0b5176f3ecebf6eca9d8a289444ea11e46dca8a5/db_info.py#L5


Refer Dummy Database

**Comment by WaterNewt** [comment]
Hey @Kool-Cool, I maybe fixed your logout button issue. I added session keys, when the user logs in, it updates the session key and adds it to the database, it also adds the session key to the browser cookies, when you press the logout button, it clears the browser cookie for the session.

**Comment by Kool-Cool** [comment]
Thanks mate :)
I really appreciate it

**Comment by Kool-Cool** [comment]
Hey @WaterNewt. 

I really appreciate your contribution 
more over, I have added the same for admin
Thanks mate :)


https://github.com/Kool-Cool/StudentPortal/blob/f963a23871058af6982215e5d4f1979bba1c5c0f/app.py#L127-L132
